name: NetMake-builder

on: push

jobs:

  build:
    name: NetMake build linux
    runs-on: ubuntu-latest
    env: 

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Get Cmake
        uses: lukka/get-cmake@latest
      
      - name: Build with Cmake
        uses: lukka/run-cmake@main
